### ISSUE TITLE
.Net MAUI

### ISSUE THREAD

**Issue by josephwambura** [dotnet-architecture/eshop-mobile-client#22]
With the new tech in town, .Net MAUI, are we going to get an update for this?

**Comment by nishanil** [comment]
Hey @josephwambura ! [MAUI is in preview](https://devblogs.microsoft.com/xamarin/whats-new-in-xamarin-and-visual-studio-2022/). We do have plans to update to MAUI however we do not have a confirmed timeline yet. We will keep you posted.
Thanks

**Comment by josephwambura** [comment]
Okay, thanks for the feedback. Let's just wait.
