### ISSUE TITLE
Missing icon resources on Windows

### ISSUE THREAD

**Issue by runceel** [dotnet-architecture/eshop-mobile-client#29]
On Windows, all icons are not displayed like below:

![image](https://user-images.githubusercontent.com/79868/189037770-7a280172-8ae0-4a17-a01f-610a046ae0e3.png)

Android is fine.
![image](https://user-images.githubusercontent.com/79868/189037867-23ea4da2-eab7-4406-b6ec-d9b455c4f4ea.png)

**Comment by runceel** [comment]
I guess `OnPlatform` tags for font family name on App.xaml don't need on MAUI:

https://github.com/dotnet-architecture/eshop-mobile-client/blob/main/eShopOnContainers/App.xaml#L93-L101

I fixed this bug changing the tags to use same font family name on all platforms:

```xml
            <OnPlatform x:Key="FontAwesomeRegular" x:TypeArguments="x:String">
                <On Platform="iOS, Android" Value="FontAwesome-Regular" />
                <On Platform="WinUI" Value="FontAwesome-Regular" />
                <!--<On Platform="WinUI" Value="Assets/Fonts/Font_Awesome_5_Free-Regular-400.otf#Font Awesome 5 Free" />-->
            </OnPlatform>

            <OnPlatform x:Key="FontAwesomeSolid" x:TypeArguments="x:String">
                <On Platform="iOS, Android" Value="FontAwesome-Solid" />
                <On Platform="WinUI" Value="FontAwesome-Solid" />
                <!--<On Platform="WinUI" Value="Assets/Fonts/Font_Awesome_5_Free-Solid-900.otf#Font Awesome 5 Free" />-->
            </OnPlatform>
```

Capture image is:
![image](https://user-images.githubusercontent.com/79868/189041344-7d458f65-ec02-4ff6-b0e2-ed373f01fc7d.png)

**Comment by jamesmontemagno** [comment]
Should be fixed now
