### ISSUE TITLE
[Mobile] Question Regarding use of ConfigureAwait(False)

### ISSUE THREAD

**Issue by EthanHipps** [dotnet-architecture/eshop-mobile-client#30]
Could you please explain why `ConfigureAwait(False)` is used with most of the HTTP requests and JSON serialization. This is the first sample MAUI app I've seen that uses it so much. Thank you in advance for any answers.

**Comment by michaelstonis** [comment]
There is a pretty great (and comprehensive) breakdown from Stephen Toub titled ["ConfigureAwait FAQ"](https://devblogs.microsoft.com/dotnet/configureawait-faq/#what-does-configureawaitfalse-do). I would highly recommend reading this.

A quick breakdown is that `ConfigureAwait(false)` allows the code to not have to return to the original calling context or scheduler. In mobile terms, the context will often be the UI thread. So, in general, for backing code (service layers, HTTP clients, database interactions) where we really don't care which thread the code executes, we can specify this to gain additional performance as the code does not need to sync back up with the original context and he can help our applications _feel better_ as this code may not continue execution on the UI thread which could make the application stutter or lock up temporarily while code is running.

**Comment by EthanHipps** [comment]
Thank you for the detailed response. I really appreciate it!
