### ISSUE TITLE
up graded app to net 7 and ran nuget packages updated ok but get this warning now 

### ISSUE THREAD

**Issue by Gerry30** [dotnet-architecture/eshop-mobile-client#34]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0618	'MessagingCenter' is obsolete: 'We recommend migrating to `CommunityToolkit.MVVM.WeakReferenceMessenger`: https://www.nuget.org/packages/CommunityToolkit.Mvvm'	eShopOnContainers (net7.0-android)	~Source\Repos\eshop-mobile-client\eShopOnContainers\ViewModels\CatalogViewModel.cs	148	Active

the associated text also has chapter on messaging centre what changes are quired to make it work

**Comment by jamesmontemagno** [comment]
Should be fixed up now
