### ISSUE TITLE
why not use Web authenticator? becuse it isn't working on Windows？

### ISSUE THREAD

**Issue by yajiegithub** [dotnet-architecture/eshop-mobile-client#42]
Web authenticator samples are necessary, this is a big trend, it seems that Microsoft doesn't care at all…………

**Comment by jamesmontemagno** [comment]
See the documentation here: https://learn.microsoft.com/en-us/dotnet/architecture/maui/authentication-and-authorization we are working on some updates.

There are many choices for auth based on your setup.

**Comment by yajiegithub** [comment]
> 请参阅此处的文档：https://learn.microsoft.com/en-us/dotnet/architecture/maui/authentication-and-authorization 我们正在进行一些更新。
> 
> 根据您的设置，身份验证有很多选择。

Tutor Maui, you are such a liar. 🤣
I have seen all your videos, and it thinks that maui is so simple and efficient to develop cross-platform applications.
After I got started, I worked on bug in stackflow/github all day.
When my bug was on Microsoft's backlog list, I tried swift & & kotlin and thought you led me astray, 🤣
