### ISSUE TITLE
[question] what's the relation to mobile client in eShop repo?

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet-architecture/eshop-mobile-client#46]
as per title: code duplication exists, while there are minor differences. Which one is moved forward? (I assume eShop repo):
https://github.com/dotnet/eShop/tree/main/src/ClientApp

Thanks!

**Comment by jamesmontemagno** [comment]
The new eShop client sample is being updated and will be the replacement for this repo. This one will be archived in the near future. We are updating the ebook currently.
