### ISSUE TITLE
Using the real microservices endpoint for the mobile app

### ISSUE THREAD

**Issue by sughosneo** [dotnet-architecture/eshop-mobile-client#7]
After setting up the actual microservices URLs in the placeholder of `Identity Url` and `Web Shopping Gateway Url`, when we click on the `[ Login ]` button, nothing happens.

![image](https://user-images.githubusercontent.com/13281246/129706590-ae0fd419-9cc1-43ef-99ef-5c7d4ec26b52.png)

Do we need to update any further configuration in the codebase?

**Comment by sughosneo** [comment]
@michaelstonis - Could you please share the steps? So that we can update the Wiki. Thank you

**Comment by michaelstonis** [comment]
The login button here should behave the same way as before. This logic was not updated.

The login button should show or launch a web browser to perform authentication. Are you not seeing that prompt?

**Comment by jamesmontemagno** [comment]
The issue here is that the service is http, so we need to enable clear-text for specific urls.

**Comment by jamesmontemagno** [comment]
https://devblogs.microsoft.com/xamarin/cleartext-http-android-network-security/

**Comment by jamesmontemagno** [comment]
We can enable clear-text for the entire app or for specific urls. it is probably best for specific urls if we document it.

**Comment by jamesmontemagno** [comment]
For iOS we need to opt out as well -> https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/ats?WT.mc_id=docs-xamarinblog-jamont#opting-out-of-ats

**Comment by bilal-dandara** [comment]
The identity api gives an error when I try to access it using 10.0.2.2 IP from the emulator. The same API works only when accessed through host.docker.internal dns alias.
